[package]

name = "claxon"
version = "0.1.0"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
description = "A FLAC decoding library"
keywords = ["flac", "lossless", "audio", "codec"]
license = "GPL-3.0"
readme = "readme.md"
homepage = "https://github.com/ruud-v-a/claxon"
repository = "https://github.com/ruud-v-a/claxon"

[dependencies]

# TODO: turn into dev-dependency (and "decode" binary into example)
hound = "1.1.0"
